# frozen_string_literal: true

require_relative "freetype/version"
require_relative "freetype/errors"
require_relative "freetype/native"
require_relative "freetype/image"
require_relative "freetype/bitmap"
require_relative "freetype/metrics"
require_relative "freetype/glyph"
require_relative "freetype/face"
require_relative "freetype/library"
require_relative "freetype/charset"
require_relative "freetype/atlas"
require_relative "freetype/pool"

module FreeType
  class << self
    def open(&block)
      Library.open(&block)
    end
  end
end

# Compatibility with the constant generated by early versions of the gem.
Freetype = FreeType unless defined?(Freetype)
